=== MemeSnorfer/Shiptest/_maps/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-04/schema",
	"title": "Ship Configuration Schema",
	"description": "A ship configuration, used for defining new ship classes.",
	"tags": "A list of tags, used for searching ships by quality.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Class Name",
			"type": "string",
			"description": "The name of the ship class, as viewable in-game."
		},
		"map_short_name": {
			"title": "Shortened Class Name",
			"type": "string",
			"description": "A shortened version of the ship class name, used in things such as the manifest.",
			"maxLength": 20
		},
		"description": {
			"title": "Class Description",
			"type": "string",
			"description": "A description of the ship class, currently only shown to admins on the shuttle manipulator, but will likely be shown to players before ship purchase in the future.",
			"minLength": 250
		},
		"tags": {
			"title": "Ship Tags",
			"type": "array",
			"description": "A list of tags describing the ship's niche, converted into searchable strings."
		},
		"prefix": {
			"title": "Ship Default Prefix",
			"type": [ "null", "string" ],
			"description": "The prefix of the ship class, appended to randomly generated names when they're first purchased.",
			"maxLength": 5
		},
		"faction_name": {
			"title": "Faction Name",
			"type": [ "null", "string" ],
			"description": "A custom faction name for the ship class. If exluded or left blank, the ship will use the default faction name for the faction that matches the ship's prefix."
		},
		"namelists": {
			"title": "Namelists",
			"type": "array",
			"description": "A list of namelists that this ship class will draw from when first bought to get a random name. All options can be found in the ship_names.json file.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"NANOTRASEN",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"DONK",
					"CLIP MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLGOV",
					"CMM-GOLD",
					"CMM-BARD",
					"PGF",
					"NV"
				]
			}
		},
		"map_path": {
			"title": "Map File Path",
			"type": "string",
			"description": "The path to the ship class's map file. Use forward slashes (/) for directories, and include the .dmm extension. Map files must be somewhere under the _maps folder.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"job_slots": {
			"title": "Job Slots",
			"description": "A list of job slots that this ship class will have when placed. The First Slot will always be the 'captain' that the purchaser becomes.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "A preset job slot, must match a job name in the code (Job names are found in the jobs' respective files)."
					},
					{
						"type": "object",
						"description": "A custom job slot, can be any name, but needs an outfit and slot count to be valid. The name is the string you are currently viewing.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "The name of the outfit that will be placed in this slot. Must be exact, will error if not found in the code.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Whether or not this slot is an officer slot. This determines if the job will have a chevron in the manifest, as well as the amount of slots cannot be changed by the crew in-round.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "The number of slots that this slot will have roundstart. The crew can change this, up to doubling it, in-round.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"roundstart": {
			"title": "Random Roundstart Selection",
			"type": "boolean",
			"description": "Whether or not the ship has a chance to be randomly selected as the free roundstart ship.",
			"default": false
		},
		"limit": {
			"title": "Ship Spawning Limit",
			"type": "integer",
			"description": "The amount of ships that can be spawned in by players in a round at once.",
			"minimum": 0,
			"maximum": 100,
			"default": 2
		},
		"starting_funds":{
			"title": "Ship Starting Funds",
			"Type": "integer",
			"description": "The amount of money a ship's bank account starts with",
			"minimum": 0,
			"maximum": 20000,
			"default": 2000
		},
		"spawn_time_coeff": {
			"title": "Required Spawn Playtime Coefficient",
			"type": "number",
			"description": "A multiplier used, along with the config value SHIP_SPAWN_BASE_EXP_MIN, to determine the amount of time a player must have spent as Living to spawn this ship from the join menu.",
			"minimum": 0,
			"default": 1
		},
		"officer_time_coeff": {
			"title": "Required Officer Playtime Coefficient",
			"type": "number",
			"description": "A multiplier used, along with the config value OFFICER_JOIN_BASE_EXP_MIN, to determine the amount of time a player must have spent as Living to spawn as an officer job on this ship AFTER it has been spawned.",
			"minimum": 0,
			"default": 1
		},
		"enabled": {
			"title": "Selectable",
			"type": "boolean",
			"description": "Whether or not this ship can be selected by players. Will still be admin-spawnable if not.",
			"default": false
		},
		"space_spawn": {
			"title": "Spawns in space",
			"type": "boolean",
			"description": "Whether this ship will spawn in space or at the outpost. If true, the ship will be placed randomly in space upon being spawned by the join menu.",
			"default": false
		}
	},

	"required": ["map_name", "map_path"]
}

=== MemeSnorfer/Shiptest/_maps/configs/independent_hotrod.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Grand Tourer-Class Recreational Vehicle",
	"prefix": "ISV",
	"namelists": ["NV"],
	"map_short_name": "GT-class",
	"map_path": "_maps/shuttles/shiptest/independent_hotrod.dmm",
	"job_slots": {
		"Passenger": {
			"outfit": "/datum/outfit/job/independent/assistant",
			"slots": 2
		}
	},
	"enabled": true
}
